"""PlannerAgent -- turn a free-form user request into a validated YAML config."""

import os
import yaml
import json_repair
from openai import OpenAI
from pathlib import Path
from typing import Dict, Any

from src.planner.schema import PlannerConfig
from src.config.profile_router import normalize_profile_name
from src.utils.prompt_loader import PromptLoader


class PlannerAgent:
    """Generate a FinSight pipeline config from a natural-language request."""

    def __init__(self):
        self.client = OpenAI(
            base_url=os.getenv("DS_BASE_URL"),
            api_key=os.getenv("DS_API_KEY"),
        )
        self.model = os.getenv("DS_MODEL_NAME", "deepseek-chat")

        # Load the prompt template via the project's PromptLoader
        prompts_dir = str(Path(__file__).parent / "prompts")
        self.prompt_loader = PromptLoader(prompts_dir)

    # ------------------------------------------------------------------
    # Core API
    # ------------------------------------------------------------------

    def generate_config(self, user_request: str) -> PlannerConfig:
        """Call the LLM and return a validated PlannerConfig."""
        prompt = self.prompt_loader.get_prompt(
            "plan_config", user_request=user_request
        )

        response = self.client.chat.completions.create(
            model=self.model,
            messages=[{"role": "user", "content": prompt}],
            response_format={"type": "json_object"},
            temperature=0.3,
        )

        raw = response.choices[0].message.content
        data = json_repair.loads(raw)
        config = PlannerConfig(**data)
        return config

    # ------------------------------------------------------------------
    # YAML helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _normalize_target_profiles(config: PlannerConfig) -> list[str]:
        profiles = [normalize_profile_name(p) for p in config.target_profiles] if config.target_profiles else []
        primary = normalize_profile_name(config.target_type)
        if not profiles:
            profiles = [primary]
        elif profiles[0] != primary:
            # Keep the model's order but enforce primary-type consistency
            profiles = [primary] + [p for p in profiles if p != primary]
        # De-duplicate while preserving order
        deduped: list[str] = []
        seen = set()
        for item in profiles:
            if item in seen:
                continue
            seen.add(item)
            deduped.append(item)
        return deduped

    def config_to_yaml_dict(self, config: PlannerConfig) -> dict:
        """Build planner overrides for the base router config."""
        profiles = self._normalize_target_profiles(config)
        output_dir = config.output_dir or f"./outputs/{config.target_name.lower().replace(' ', '-')}"
        yaml_dict: Dict[str, Any] = {
            "target_name": config.target_name,
            "stock_code": config.stock_code,
            "target_type": profiles[0],
            "target_profiles": profiles,
            "market": config.market,
            "output_dir": output_dir,
            "language": config.language,
            # Request-specific task lists generated by planner
            "custom_collect_tasks": config.custom_collect_tasks,
            "custom_analysis_tasks": config.custom_analysis_tasks,
        }
        return yaml_dict

    @staticmethod
    def write_yaml(yaml_dict: dict, path: str) -> None:
        """Safely write a dict to a YAML file (never writes raw LLM text)."""
        os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
        with open(path, "w", encoding="utf-8") as fh:
            yaml.dump(
                yaml_dict,
                fh,
                default_flow_style=False,
                allow_unicode=True,
                sort_keys=False,
            )

    # ------------------------------------------------------------------
    # End-to-end convenience
    # ------------------------------------------------------------------

    def plan(self, user_request: str, yaml_path: str = "my_config.yaml") -> dict:
        """Full pipeline: LLM -> validate -> merge into router config -> write YAML."""
        config = self.generate_config(user_request)
        planner_overrides = self.config_to_yaml_dict(config)
        existing: Dict[str, Any] = {}
        if os.path.exists(yaml_path):
            with open(yaml_path, "r", encoding="utf-8") as fh:
                existing = yaml.safe_load(fh) or {}
            if not isinstance(existing, dict):
                existing = {}
        merged = {**existing, **planner_overrides}
        self.write_yaml(merged, yaml_path)
        return planner_overrides
